"""kpi tables

Revision ID: e59726afa6cf
Revises: deccdebcb43a
Create Date: 2025-01-21 16:33:53.458504

"""



# revision identifiers, used by Alembic.
revision = "e59726afa6cf"
down_revision = "deccdebcb43a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
