"""kpi tables

Revision ID: 19c8a01c82ae
Revises: e59726afa6cf
Create Date: 2025-01-21 16:42:53.333825

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "19c8a01c82ae"
down_revision = "e59726afa6cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cyes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fstb",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lgrk",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "oval",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ovar",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rfct",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sape",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sown",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sown")
    op.drop_table("sape")
    op.drop_table("rfct")
    op.drop_table("ovar")
    op.drop_table("oval")
    op.drop_table("news")
    op.drop_table("lgrk")
    op.drop_table("fstb")
    op.drop_table("cyes")
    # ### end Alembic commands ###
